import mongoose, { Schema, Document } from 'mongoose';

export interface IProducto extends Document {
    id_wc: number; // WooCommerce ID
    name: string;
    sku: string;
    price: number;
    regular_price: number;
    sale_price: number;
    stock_quantity: number;
    stock_status: string;
    status: string;
    categories: Array<{ id: number; name: string }>;
    images: Array<{ src: string }>;
    attributes: Array<any>;
}

const ProductoSchema: Schema = new Schema({
    id_wc: { type: Number, unique: true, sparse: true }, // Optional, generated by WooCommerce
    name: { type: String },
    sku: { type: String, required: true, index: true },
    price: { type: Number, default: 0 },
    regular_price: { type: Number, default: 0 },
    sale_price: { type: Number, default: 0 },
    stock_quantity: { type: Number, default: 0 },
    stock_status: { type: String, default: 'instock' },
    status: { type: String, default: 'publish' },
    categories: { type: Array, default: [] },
    images: { type: Array, default: [] },
    attributes: { type: Array, default: [] },
    // V1 Legacy fields mapped from the Excel upload
    Nombre: { type: String },
    Código: { type: String },
    Modelo: { type: String },
    Ref: { type: String },
    Marca: { type: String },
    "Existencia Actual": { type: Number, default: 0 },
    "Precio Minimo": { type: Number, default: 0 },
    "Precio Mayor": { type: Number, default: 0 },
    "Precio Oferta": { type: Number, default: 0 }
}, {
    timestamps: true,
    strict: false // Allows dynamic fields from Excel without throwing validation errors
});

export const Producto = mongoose.models.Producto || mongoose.model<IProducto>('Producto', ProductoSchema, 'productos');
